framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            
            # Transport pour notifications emails
            email_notifications:
                dsn: 'doctrine://default?queue_name=email_notifications'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
            
            # Transport pour notifications praticiens
            practitioner_notifications:
                dsn: 'doctrine://default?queue_name=practitioner_notifications'
                retry_strategy:
                    max_retries: 3
                    delay: 2000
                    multiplier: 2
            
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: email_notifications
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            
            # Messages personnalisés pour notifications
            'App\Message\PatientActivationNotification': email_notifications
            'App\Message\PractitionerNotification': practitioner_notifications
            'App\Message\BilanReadyNotification': email_notifications

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
