
services:
    mailer:
        image: schickling/mailcatcher
        ports:
            - "1025:1025"
            - "1080:1080"

    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
